package com.mycompany.perfectstrangers;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ephex
 */
public class PSInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PSInicio.class.getName());

    /**
     * Creates new form PSInicio
     */
    public PSInicio() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);        
        try {
            java.net.URL iconURL = getClass().getResource("/com/mycompany/perfectstrangers/icon.png");
            if (iconURL != null) {
                this.setIconImage(new javax.swing.ImageIcon(iconURL).getImage());
            }
        } catch (Exception e) {
            System.err.println("No se pudo cargar el icono de la ventana.");
        }
        
        this.setTitle("PerfectStrangers - VENTA Y ORDENES");
                jPFContraseña.setEchoChar('*');
        jPFContraseña.setText("");
        jLAccesoIncorrecto.setText("");
        jBAcceder.addActionListener(evt -> autenticarUsuario());
        
        // Centrar el contenido dinámicamente
        javax.swing.JPanel fondoCentrado = new javax.swing.JPanel(new java.awt.GridBagLayout());
        fondoCentrado.setBackground(new java.awt.Color(0, 0, 0));
        fondoCentrado.add(jPPrincipal);
        this.setContentPane(fondoCentrado);        
        try {
            java.net.URL logoURL = getClass().getResource("/com/mycompany/perfectstrangers/icon.png");
            if (logoURL != null) {
                javax.swing.ImageIcon logoOriginal = new javax.swing.ImageIcon(logoURL);
                java.awt.Image imagenOriginal = logoOriginal.getImage();
                java.awt.Image redimensionada = imagenOriginal.getScaledInstance(250, 250, java.awt.Image.SCALE_SMOOTH);
                jLLogo.setIcon(new javax.swing.ImageIcon(redimensionada));
            }
        } catch (Exception e) {}    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPrincipal = new javax.swing.JPanel();
        jLContraseña = new javax.swing.JLabel();
        jLUsuario = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jPFContraseña = new javax.swing.JPasswordField();
        jLLogo = new javax.swing.JLabel();
        jBAcceder = new javax.swing.JButton();
        jLAccesoIncorrecto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        jLContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLContraseña.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLContraseña.setText("Contraseña");

        jLUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLUsuario.setText("Usuario");

        jTFUsuario.setText("Usuario");
        jTFUsuario.addActionListener(this::jTFUsuarioActionPerformed);

        jPFContraseña.setText("");

        jLLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/perfectstrangers/logo150.png"))); // NOI18N
        jLLogo.setMaximumSize(new java.awt.Dimension(600, 600));
        jLLogo.setMinimumSize(new java.awt.Dimension(600, 600));
        jLLogo.setPreferredSize(new java.awt.Dimension(600, 600));

        jBAcceder.setText("Acceder");

        jLAccesoIncorrecto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLAccesoIncorrecto.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jBAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPPrincipalLayout.createSequentialGroup()
                                .addComponent(jLUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPPrincipalLayout.createSequentialGroup()
                                .addComponent(jLContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPFContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLAccesoIncorrecto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLUsuario)
                            .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLContraseña)
                            .addComponent(jPFContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jBAcceder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLAccesoIncorrecto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuarioActionPerformed

    private void autenticarUsuario() {
        String usuario = jTFUsuario.getText().trim();
        String password = new String(jPFContraseña.getPassword());

        if (usuario.isEmpty() || password.isEmpty()) {
            jLAccesoIncorrecto.setText("Usuario y contraseña son obligatorios.");
            return;
        }

        String sql = "SELECT u.id_empleado, e.nombre, e.ap_paterno, e.puesto " +
                     "FROM usuarios u " +
                     "JOIN empleados e ON u.id_empleado = e.id_empleado " +
                     "WHERE u.usuario = ? AND u.contrasena = SHA2(?, 256)";

        try (Connection connection = DBConnection.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, usuario);
            statement.setString(2, password);

            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    Sesion.idEmpleado = resultSet.getInt("id_empleado");
                    String nombre = resultSet.getString("nombre");
                    String ap = resultSet.getString("ap_paterno");
                    Sesion.nombreEmpleado = (nombre != null ? nombre.trim() : "") + 
                                            (ap != null ? " " + ap.trim() : "");
                    Sesion.puestoEmpleado = resultSet.getString("puesto") != null ? resultSet.getString("puesto").trim() : "Empleado";

                    jLAccesoIncorrecto.setText("");
                    java.awt.EventQueue.invokeLater(() -> new PSMenu().setVisible(true));
                    dispose();
                } else {
                    jLAccesoIncorrecto.setText("Usuario o contraseña incorrectos.");
                }
            }
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Error al validar credenciales", ex);
            jLAccesoIncorrecto.setText("No fue posible conectar con la base de datos.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.put("Button.arc", 20);
            javax.swing.UIManager.put("Component.arc", 20);
            javax.swing.UIManager.put("ProgressBar.arc", 20);
            javax.swing.UIManager.put("TextComponent.arc", 20);
            javax.swing.UIManager.put("ScrollBar.arc", 20);
            com.formdev.flatlaf.themes.FlatMacDarkLaf.setup();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PSInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAcceder;
    private javax.swing.JLabel jLAccesoIncorrecto;
    private javax.swing.JLabel jLContraseña;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JPasswordField jPFContraseña;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
