/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perfectstrangers;

/**
 *
 * @author Ephex
 */
public class PSMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PSMenu.class.getName());

    /**
     * Creates new form PSMenu
     */
    public PSMenu() {
        initComponents();
        configurarNavegacionMenu();
        configurarFondo();
    }

    private void configurarFondo() {
        try {
            // Removemos el layout generado de NetBeans para jPPrincipal
            jPPrincipal.removeAll();
            jPPrincipal.setLayout(new java.awt.BorderLayout());
            
            // Creamos un JLabel para el GIF
            java.net.URL urlGif = getClass().getResource("/com/mycompany/perfectstrangers/Animación_en_Bucle_Lista.gif");
            javax.swing.JLabel labelFondo = new javax.swing.JLabel();
            if (urlGif != null) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(urlGif);
                labelFondo.setIcon(icon);
                labelFondo.setHorizontalAlignment(javax.swing.JLabel.CENTER);
            } else {
                // Alternativa por si el recurso no lo carga correctamente via classpath (si no se ha compilado)
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon("src/main/java/com/mycompany/perfectstrangers/Animación_en_Bucle_Lista.gif");
                labelFondo.setIcon(icon);
                labelFondo.setHorizontalAlignment(javax.swing.JLabel.CENTER);
            }
            
            // Reagregamos los componentes
            jPPrincipal.add(labelFondo, java.awt.BorderLayout.CENTER);
            jPPrincipal.add(jMenuInf, java.awt.BorderLayout.SOUTH);
            
            jPPrincipal.revalidate();
            jPPrincipal.repaint();
        } catch (Exception e) {
            logger.log(java.util.logging.Level.WARNING, "No se pudo cargar el GIF de fondo.", e);
        }
    }

    private void configurarNavegacionMenu() {
        JInicio.addMenuListener(new javax.swing.event.MenuListener() {
            @Override
            public void menuSelected(javax.swing.event.MenuEvent e) {
                // Ya en Inicio/Menú principal, no hacemos nada para evitar ir al login
            }

            @Override
            public void menuDeselected(javax.swing.event.MenuEvent e) {
            }

            @Override
            public void menuCanceled(javax.swing.event.MenuEvent e) {
            }
        });

        jMOTomar.addActionListener(evt -> abrirVentana(new PSTOrden()));
        jMOConsultar.addActionListener(evt -> abrirVentana(new PSConOrder()));
        jMOCobrar.addActionListener(evt -> abrirVentana(new PSCobOrden()));

        JInventario.addMenuListener(new javax.swing.event.MenuListener() {
            @Override
            public void menuSelected(javax.swing.event.MenuEvent e) {
                abrirVentana(new PSInventario());
            }

            @Override
            public void menuDeselected(javax.swing.event.MenuEvent e) {
            }

            @Override
            public void menuCanceled(javax.swing.event.MenuEvent e) {
            }
        });

        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            @Override
            public void menuSelected(javax.swing.event.MenuEvent e) {
                abrirVentana(new PSHistorial());
            }

            @Override
            public void menuDeselected(javax.swing.event.MenuEvent e) {
            }

            @Override
            public void menuCanceled(javax.swing.event.MenuEvent e) {
            }
        });

        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            @Override
            public void menuSelected(javax.swing.event.MenuEvent e) {
                System.exit(0);
            }

            @Override
            public void menuDeselected(javax.swing.event.MenuEvent e) {
            }

            @Override
            public void menuCanceled(javax.swing.event.MenuEvent e) {
            }
        });
    }

    private void abrirVentana(javax.swing.JFrame ventana) {
        java.awt.EventQueue.invokeLater(() -> ventana.setVisible(true));
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPPrincipal = new javax.swing.JPanel();
        jMenuInf = new javax.swing.JPanel();
        jLUsuario = new javax.swing.JLabel();
        jUsuario = new javax.swing.JLabel();
        jLPuesto = new javax.swing.JLabel();
        jPuesto = new javax.swing.JLabel();
        jLTiempo = new javax.swing.JLabel();
        jTiempo = new javax.swing.JLabel();
        jMenuSup = new javax.swing.JMenuBar();
        JInicio = new javax.swing.JMenu();
        jMenu = new javax.swing.JMenu();
        jMOrdenes = new javax.swing.JMenu();
        jMOTomar = new javax.swing.JMenuItem();
        jMOConsultar = new javax.swing.JMenuItem();
        jMOCobrar = new javax.swing.JMenuItem();
        JInventario = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        jMenuInf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, null, null));

        jLUsuario.setText("Usuario: ");

        jUsuario.setText("-");

        jLPuesto.setText("Puesto: ");

        jPuesto.setText("-");

        jLTiempo.setText("Tiempo: ");

        jTiempo.setText("99:99:99");

        javax.swing.GroupLayout jMenuInfLayout = new javax.swing.GroupLayout(jMenuInf);
        jMenuInf.setLayout(jMenuInfLayout);
        jMenuInfLayout.setHorizontalGroup(
            jMenuInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuInfLayout.createSequentialGroup()
                .addComponent(jLUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTiempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 92, Short.MAX_VALUE))
        );
        jMenuInfLayout.setVerticalGroup(
            jMenuInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addComponent(jUsuario)
                .addComponent(jLPuesto)
                .addComponent(jPuesto)
                .addComponent(jLTiempo)
                .addComponent(jTiempo))
        );

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMenuInf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                .addGap(0, 348, Short.MAX_VALUE)
                .addComponent(jMenuInf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JInicio.setText("Inicio");
        jMenuSup.add(JInicio);

        jMenu.setText("Menú");
        jMenuSup.add(jMenu);

        jMOrdenes.setText("Ordenes");

        jMOTomar.setText("Tomar");
        jMOrdenes.add(jMOTomar);

        jMOConsultar.setText("Consultar");
        jMOrdenes.add(jMOConsultar);

        jMOCobrar.setText("Cobrar");
        jMOrdenes.add(jMOCobrar);

        jMenuSup.add(jMOrdenes);

        JInventario.setText("Inventario");
        jMenuSup.add(JInventario);

        jMenu1.setText("Historial");
        jMenuSup.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuSup.add(jMenu2);

        setJMenuBar(jMenuSup);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PSMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JInicio;
    private javax.swing.JMenu JInventario;
    private javax.swing.JLabel jLPuesto;
    private javax.swing.JLabel jLTiempo;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JMenuItem jMOCobrar;
    private javax.swing.JMenuItem jMOConsultar;
    private javax.swing.JMenuItem jMOTomar;
    private javax.swing.JMenu jMOrdenes;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jMenuInf;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar jMenuSup;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPuesto;
    private javax.swing.JLabel jTiempo;
    private javax.swing.JLabel jUsuario;
    // End of variables declaration//GEN-END:variables
}
