/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perfectstrangers;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ephex
 */
public class PSTOrden extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PSTOrden.class.getName());

    private JPanel panelProductos;
    private List<ProductoItem> productosActuales;
    private DefaultTableModel modeloOrden;
    private JTable tablaOrden;

    class ProductoItem {
        int id;
        String nombre;
        double precio;
        boolean isPaquete;
        JCheckBox checkBox;
        JSpinner spinnerCantidad;
        JPanel panel;
        
        public ProductoItem(int id, String nombre, double precio, boolean isPaquete) {
            this.id = id;
            this.nombre = nombre;
            this.precio = precio;
            this.isPaquete = isPaquete;
            
            panel = new JPanel(new java.awt.BorderLayout(10, 0));
            panel.setBackground(new java.awt.Color(30, 30, 30));
            panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
            panel.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 60)); // Limitar la altura para el BoxLayout
            
            checkBox = new JCheckBox(nombre + " - $" + precio);
            checkBox.setBackground(new java.awt.Color(30, 30, 30));
            checkBox.setForeground(new java.awt.Color(255, 255, 255));
            checkBox.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
            
            // Selector de cantidad
            spinnerCantidad = new JSpinner(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
            spinnerCantidad.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
            spinnerCantidad.setPreferredSize(new java.awt.Dimension(80, 35));
            
            panel.add(checkBox, java.awt.BorderLayout.CENTER);
            panel.add(spinnerCantidad, java.awt.BorderLayout.EAST);
        }
    }

    /**
     * Creates new form PSTOrden
     */
    public PSTOrden() {
        initComponents();
        
        jBAgregar.setBackground(null);
        jBRegistrar.setBackground(null);
        jBRegresar.setBackground(null);
        jBCombos.setBackground(null);
        jBPlatillos.setBackground(null);
        jBBebidas.setBackground(null);
        
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        try {
            java.net.URL iconURL = getClass().getResource("/com/mycompany/perfectstrangers/icon.png");
            if (iconURL != null) {
                this.setIconImage(new javax.swing.ImageIcon(iconURL).getImage());
            }
        } catch (Exception e) {}
        this.setTitle("PerfectStrangers - Tomar Orden");

        jBRegresar.addActionListener(evt -> {
            java.awt.EventQueue.invokeLater(() -> new PSMenu().setVisible(true));
            dispose();
        });
        configurarInterfaz();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPrincipal = new javax.swing.JPanel();
        jPCont = new javax.swing.JPanel();
        jBAgregar = new javax.swing.JButton();
        jBCombos = new javax.swing.JButton();
        jBPlatillos = new javax.swing.JButton();
        jBBebidas = new javax.swing.JButton();
        jPOrden = new javax.swing.JPanel();
        jLOrden = new javax.swing.JLabel();
        jBRegistrar = new javax.swing.JButton();
        jCNoMesa = new javax.swing.JComboBox<>();
        jLNVentana = new javax.swing.JLabel();
        jBRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        jPCont.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBAgregar.setBackground(new java.awt.Color(204, 204, 204));
        jBAgregar.setText("AGREGAR");
        jBAgregar.addActionListener(this::jBAgregarActionPerformed);

        javax.swing.GroupLayout jPContLayout = new javax.swing.GroupLayout(jPCont);
        jPCont.setLayout(jPContLayout);
        jPContLayout.setHorizontalGroup(
            jPContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContLayout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPContLayout.setVerticalGroup(
            jPContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPContLayout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jBCombos.setText("Combos");

        jBPlatillos.setText("Platillos");

        jBBebidas.setText("Bebidas");
        jBBebidas.addActionListener(this::jBBebidasActionPerformed);

        jPOrden.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLOrden.setText("-");

        jBRegistrar.setBackground(new java.awt.Color(204, 204, 204));
        jBRegistrar.setText("REGISTRAR");

        jCNoMesa.addActionListener(this::jCNoMesaActionPerformed);

        javax.swing.GroupLayout jPOrdenLayout = new javax.swing.GroupLayout(jPOrden);
        jPOrden.setLayout(jPOrdenLayout);
        jPOrdenLayout.setHorizontalGroup(
            jPOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOrdenLayout.createSequentialGroup()
                .addGroup(jPOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPOrdenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(jLOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jCNoMesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPOrdenLayout.setVerticalGroup(
            jPOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOrdenLayout.createSequentialGroup()
                .addComponent(jCNoMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLNVentana.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLNVentana.setForeground(new java.awt.Color(255, 255, 255));
        jLNVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNVentana.setText("TOMA DE ORDENES");

        jBRegresar.setBackground(new java.awt.Color(204, 204, 204));
        jBRegresar.setText("REGRESAR");

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jPOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPPrincipalLayout.createSequentialGroup()
                                .addComponent(jBPlatillos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNVentana)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBPlatillos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBRegresar)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBebidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBebidasActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void configurarInterfaz() {
        // --- HACER RESPONSIVA LA VENTANA COMPLETA ---
        jPPrincipal.removeAll();
        jPPrincipal.setLayout(new java.awt.BorderLayout(10, 10));
        jPPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        // Título arriba
        jLNVentana.setFont(new java.awt.Font("Segoe UI", 1, 24));
        jLNVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPPrincipal.add(jLNVentana, java.awt.BorderLayout.NORTH);

        // Panel Central dividido en dos (Izquierda Productos, Derecha Orden)
        javax.swing.JPanel panelCentro = new javax.swing.JPanel(new java.awt.GridLayout(1, 2, 20, 0));
        panelCentro.setBackground(new java.awt.Color(0, 0, 0));

        // 1. Lado Izquierdo (Productos)
        javax.swing.JPanel panelIzquierdo = new javax.swing.JPanel(new java.awt.BorderLayout(0, 10));
        panelIzquierdo.setBackground(new java.awt.Color(0, 0, 0));
        
        // Botones de Categoría arriba del lado izquierdo
        javax.swing.JPanel panelCategorias = new javax.swing.JPanel(new java.awt.GridLayout(1, 3, 5, 0));
        panelCategorias.setBackground(new java.awt.Color(0, 0, 0));
        panelCategorias.add(jBPlatillos);
        panelCategorias.add(jBCombos);
        panelCategorias.add(jBBebidas);
        panelIzquierdo.add(panelCategorias, java.awt.BorderLayout.NORTH);
        panelIzquierdo.add(jPCont, java.awt.BorderLayout.CENTER);

        // 2. Lado Derecho (Orden)
        panelCentro.add(panelIzquierdo);
        panelCentro.add(jPOrden);

        jPPrincipal.add(panelCentro, java.awt.BorderLayout.CENTER);

        // Botón regresar abajo
        javax.swing.JPanel panelInferior = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        panelInferior.setBackground(new java.awt.Color(0, 0, 0));
        panelInferior.add(jBRegresar);
        jPPrincipal.add(panelInferior, java.awt.BorderLayout.SOUTH);
        // ---------------------------------------------
        
        // Init mesas
        jCNoMesa.removeAllItems();
        for (int i = 1; i <= 10; i++) {
            jCNoMesa.addItem("Mesa " + i);
        }

        // Reconfigurar contenedor de productos (jPCont)
        jPCont.setLayout(new BorderLayout());
        jPCont.removeAll(); 
        
        panelProductos = new JPanel();
        panelProductos.setLayout(new BoxLayout(panelProductos, BoxLayout.Y_AXIS));
        panelProductos.setBackground(new java.awt.Color(0, 0, 0));
        JScrollPane scrollProductos = new JScrollPane(panelProductos);
        jPCont.add(scrollProductos, BorderLayout.CENTER);
        
        JPanel panelInferiorProductos = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        panelInferiorProductos.setBackground(new java.awt.Color(0, 0, 0));
        jBAgregar.setText("AGREGAR");
        panelInferiorProductos.add(jBAgregar);
        jPCont.add(panelInferiorProductos, BorderLayout.SOUTH);
        
        // Reconfigurar contenedor de Orden (jPOrden)
        jPOrden.setLayout(new BorderLayout(5, 5));
        jPOrden.removeAll();
        jPOrden.setBackground(new java.awt.Color(0, 0, 0));
        jPOrden.add(jCNoMesa, BorderLayout.NORTH);
        
        modeloOrden = new DefaultTableModel(new Object[]{"ID", "Nombre", "Precio", "Cant.", "IsPaquete"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 3; // Solo permitir editar cantidad
            }
        };
        tablaOrden = new JTable(modeloOrden);
        // Ocultar columna 4 (IsPaquete)
        tablaOrden.getColumnModel().getColumn(4).setMinWidth(0);
        tablaOrden.getColumnModel().getColumn(4).setMaxWidth(0);
        tablaOrden.getColumnModel().getColumn(4).setWidth(0);
        
        // Alinear celdas al centro y ajustar anchos de columnas
        javax.swing.table.DefaultTableCellRenderer centerRender = new javax.swing.table.DefaultTableCellRenderer();
        centerRender.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for(int i = 0; i < 4; i++){
            tablaOrden.getColumnModel().getColumn(i).setCellRenderer(centerRender);
        }
        tablaOrden.getColumnModel().getColumn(0).setPreferredWidth(50);
        tablaOrden.getColumnModel().getColumn(1).setPreferredWidth(250);
        tablaOrden.getColumnModel().getColumn(2).setPreferredWidth(80);
        tablaOrden.getColumnModel().getColumn(3).setPreferredWidth(50);

        JScrollPane scrollOrden = new JScrollPane(tablaOrden);
        jPOrden.add(scrollOrden, BorderLayout.CENTER);
        
        JPanel panelInferiorOrden = new JPanel(new FlowLayout(FlowLayout.CENTER));
        panelInferiorOrden.setBackground(new java.awt.Color(0, 0, 0));
        JButton btnEliminar = new JButton("Quitar de la lista");
        btnEliminar.addActionListener(e -> borrarSeleccionados());
        panelInferiorOrden.add(btnEliminar);
        panelInferiorOrden.add(jBRegistrar);
        
        jPOrden.add(panelInferiorOrden, BorderLayout.SOUTH);

        jPCont.revalidate();
        jPCont.repaint();
        jPOrden.revalidate();
        jPOrden.repaint();

        // Listeners for Categories matching the UI buttons
        jBPlatillos.setText("Platillos");
        jBCombos.setText("Combos");
        jBBebidas.setText("Bebidas");
        
        jBPlatillos.addActionListener(e -> cargarProductos("Platillos"));
        jBCombos.addActionListener(e -> cargarProductos("Combos"));
        jBBebidas.addActionListener(e -> cargarProductos("Bebidas"));

        // Remove old action listeners if any or just set the new ones
        for (java.awt.event.ActionListener al : jBAgregar.getActionListeners()) {
            jBAgregar.removeActionListener(al);
        }
        for (java.awt.event.ActionListener al : jBRegistrar.getActionListeners()) {
            jBRegistrar.removeActionListener(al);
        }
        
        jBAgregar.addActionListener(e -> agregarAOrden());
        jBRegistrar.addActionListener(e -> registrarOrden());
        
        // Load default category
        cargarProductos("Platillos");
    }

    private void cargarProductos(String categoria) {
        panelProductos.removeAll();
        productosActuales = new ArrayList<>();
        
        String query = "";
        boolean isPaquete = false;
        // Adaptamos a las columnas de la nueva bd
        if (categoria.equals("Platillos")) {
            query = "SELECT id_platillo AS id, nombre_alimento AS nombre, costo FROM platillos WHERE tipo_alimento NOT LIKE '%Bebida%'";
        } else if (categoria.equals("Bebidas")) {
            query = "SELECT id_platillo AS id, nombre_alimento AS nombre, costo FROM platillos WHERE tipo_alimento LIKE '%Bebida%'";
        } else if (categoria.equals("Combos")) {
            // Suponemos que los nombres han cambiado en bd: id_paquete, nombre_paquete, precio_paquete
            query = "SELECT MAX(id_paquete) AS id, nombre_paquete AS nombre, MAX(precio_paquete) AS costo FROM paquetes WHERE id_paquete != 0 GROUP BY nombre_paquete";
            isPaquete = true;
        }

        try (Connection con = DBConnection.getConnection();
             PreparedStatement pst = con.prepareStatement(query);
             ResultSet rs = pst.executeQuery()) {
             
            while (rs.next()) {
                int id = rs.getInt("id");
                String nombre = rs.getString("nombre");
                double costo = rs.getDouble("costo");
                
                ProductoItem item = new ProductoItem(id, nombre, costo, isPaquete);
                productosActuales.add(item);
                
                // Agregar el panel con checkBox y Spinner
                panelProductos.add(item.panel);
                // Espaciador entre elementos
                panelProductos.add(Box.createRigidArea(new java.awt.Dimension(0, 5)));
            }
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error base de datos: " + ex.getMessage());
        }
        
        panelProductos.revalidate();
        panelProductos.repaint();
    }

    private void agregarAOrden() {
        if (productosActuales == null) return;
        for (ProductoItem item : productosActuales) {
            if (item.checkBox.isSelected()) {
                int cantidad = (int) item.spinnerCantidad.getValue();
                modeloOrden.addRow(new Object[]{ item.id, item.nombre, item.precio, cantidad, item.isPaquete });
                item.checkBox.setSelected(false);
                item.spinnerCantidad.setValue(1); // Resetear spinner
            }
        }
    }

    private void borrarSeleccionados() {
        int[] seleccionados = tablaOrden.getSelectedRows();
        for (int i = seleccionados.length - 1; i >= 0; i--) {
            modeloOrden.removeRow(seleccionados[i]);
        }
    }

    private void registrarOrden() {
        if (modeloOrden.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "La orden está vacía. Selecciona productos primero.");
            return;
        }
        String mesaStr = jCNoMesa.getSelectedItem().toString();
        int numMesa = 1;
        try { numMesa = Integer.parseInt(mesaStr.replace("Mesa ", "").trim()); } catch (Exception e){}

        int idEmpleado = 1; 
        if (Sesion.idEmpleado > 0) idEmpleado = Sesion.idEmpleado;

        try (Connection con = DBConnection.getConnection()) {
            con.setAutoCommit(false);
            
            int idPaquete = 0;
            for (int i = 0; i < modeloOrden.getRowCount(); i++) {
                boolean isPaq = false;
                try { isPaq = (boolean) modeloOrden.getValueAt(i, 4); } catch (Exception e){}
                if (isPaq) {
                    idPaquete = (int) modeloOrden.getValueAt(i, 0);
                    break;
                }
            }
            
            int idOrden = 1;
            try(java.sql.Statement st = con.createStatement(); 
                ResultSet rsId = st.executeQuery("SELECT MAX(id_orden) FROM ordenes")) {
                if(rsId.next()) {
                    idOrden = rsId.getInt(1) + 1;
                }
            }

            String sqlOrden = "INSERT INTO ordenes (id_orden, id_empleado, id_paquete, mesa, fecha, hora, estado) VALUES (?, ?, ?, ?, CURDATE(), CURTIME(), 'Levantada')";
            try(PreparedStatement pstO = con.prepareStatement(sqlOrden)) {
                pstO.setInt(1, idOrden);
                pstO.setInt(2, idEmpleado);
                pstO.setInt(3, idPaquete);
                pstO.setInt(4, numMesa);
                pstO.executeUpdate();
            }

            String sqlDetalle = "INSERT INTO detalle_orden (id_orden, id_platillo, cant) VALUES (?, ?, ?)";
            try (PreparedStatement pstD = con.prepareStatement(sqlDetalle)) {
                boolean tieneDetalles = false;
                for (int i = 0; i < modeloOrden.getRowCount(); i++) {
                    boolean isPaq = false;
                    try { isPaq = (boolean) modeloOrden.getValueAt(i, 4); } catch (Exception e){}
                    
                    if (!isPaq) {
                        int idItem = (int) modeloOrden.getValueAt(i, 0);
                        Object cantObj = modeloOrden.getValueAt(i, 3);
                        int cant = 1;
                        if (cantObj instanceof Integer) {
                            cant = (Integer) cantObj;
                        } else if (cantObj instanceof String) {
                            try { cant = Integer.parseInt((String) cantObj); } catch (Exception e) { }
                        }
                        
                        pstD.setInt(1, idOrden);
                        pstD.setInt(2, idItem);
                        pstD.setInt(3, cant);
                        pstD.addBatch();
                        tieneDetalles = true;
                    }
                }
                if (tieneDetalles) {
                    pstD.executeBatch();
                }
            }
            
            con.commit();
            javax.swing.JOptionPane.showMessageDialog(this, "¡Orden " + idOrden + " registrada con éxito para la " + mesaStr + "!");
            modeloOrden.setRowCount(0);
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar en BD: " + ex.getMessage());
        }
    }

    private void jCNoMesaActionPerformed(java.awt.event.ActionEvent evt) {
        // ...
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.put("Button.arc", 20);
            javax.swing.UIManager.put("Component.arc", 20);
            javax.swing.UIManager.put("ProgressBar.arc", 20);
            javax.swing.UIManager.put("TextComponent.arc", 20);
            javax.swing.UIManager.put("ScrollBar.arc", 20);
            com.formdev.flatlaf.themes.FlatMacDarkLaf.setup();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PSTOrden().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBebidas;
    private javax.swing.JButton jBCombos;
    private javax.swing.JButton jBPlatillos;
    private javax.swing.JButton jBRegistrar;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JComboBox<String> jCNoMesa;
    private javax.swing.JLabel jLNVentana;
    private javax.swing.JLabel jLOrden;
    private javax.swing.JPanel jPCont;
    private javax.swing.JPanel jPOrden;
    private javax.swing.JPanel jPPrincipal;
    // End of variables declaration//GEN-END:variables
}
